### ISSUE TITLE
filter_by_count.py error

### ISSUE THREAD

**Issue by yuqiu77** [Magdoll/cDNA_Cupcake#105]
Use Cupcake 9.0.3 after running isoseq3.2.2. 
Since isoseq 3.2.2 only produce hq.fasta and not hq.fastq, I used it for the minimap alignment, collapse and get_abundance step.  However, the get_abundance step would only generate a rep.fa while filter_by_count.py need a rep.fq file.  Therefore, I got the following error msg:

Traceback (most recent call last):
  File "/opt/conda/bin/filter_by_count.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==9.0.3', 'filter_by_count.py')
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/conda/lib/python3.7/site-packages/cupcake-9.0.3-py3.7-linux-x86_64.egg/EGG-INFO/scripts/filter_by_count.py", line 106, in <module>
    filter_by_count(args.input_prefix, output_prefix, args.min_count, args.dun_use_group_count)
  File "/opt/conda/lib/python3.7/site-packages/cupcake-9.0.3-py3.7-linux-x86_64.egg/EGG-INFO/scripts/filter_by_count.py", line 75, in filter_by_count
    for r in SeqIO.parse(open(rep_filename), 'fastq'):
FileNotFoundError: [Errno 2] No such file or directory: 'sample.collapsed.rep.fq'

Any workaround?

**Comment by Magdoll** [comment]
fasta should not be supported in Cupcake v9.1.0 for both `filter_away_subset.py` and `filter_by_count.py`.

https://github.com/Magdoll/cDNA_Cupcake/tree/v9.1.0

--Liz
