### ISSUE TITLE
collapse_isoforms_by_sam.py: "ValueError: Sequence and quality captions differ."

### ISSUE THREAD

**Issue by ejh243** [Magdoll/cDNA_Cupcake#107]
Hi Liz, 

I have been following your iso-seq3 tutorial, and I am now trying to use Cupcake to further process the output. I am having a few issues with collapse_isoforms_by_sam.py.

1) The output of the cluster step in isoseq is polished.hq.fasta.gz but the input for the alignment steps and collapse_isoforms_by_sam.py is a fastq file: hq_isoforms.fastq. Is it simply a case of using the script fa2fq.py to convert to the fastq version? 

2) I have run fa2fq.py so I have a fasta and fastq version of the output of the cluster step and have aligned both with minimap2, interestingly I get a bigger bam file with fastq. I then tried to use collapse_isoforms_by_sam.py, but I get this error: 

`collapse_isoforms_by_sam.py --input Cluster/polished.hq.fastq.gz --fq    -s Aligned/hq_isoforms.fastq.sorted.sam --dun-merge-5-shorter -o collapsed_isoforms

Traceback (most recent call last):
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==8.7.4', 'collapse_isoforms_by_sam.py')
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/cupcake-8.7.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 240, in <module>
    main(args)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/cupcake-8.7.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 169, in main
    check_ids_unique(args.input, is_fq=args.fq)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/cupcake-8.7.4-py2.7-linux-x86_64.egg/cupcake/tofu/utils.py", line 11, in check_ids_unique
    for r in SeqIO.parse(open(fa_or_fq_filename), 'fastq' if is_fq else 'fasta'):
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1031, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 920, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
ValueError: Sequence and quality captions differ.
`

I have run the test data successfully so I think the error is in my fastq file? Have I missed any steps?

Many Thanks

Eilis

**Comment by Magdoll** [comment]
Hi @ejh243 ,

1. `collapse_isoforms_by_sam.py` can accept both FASTA and FASTQ input. If you have HQ fasta, you should use `--input hq.fasta` without the `--fq` option. 

2. `collapse_isoforms_by_sam.py` does not accept gzip input, that is likely where the errors is coming from?

**Comment by ejh243** [comment]
I was using unzipped files. I tried both the fasta and fastq files. With fasta I got a different error: 

collapse_isoforms_by_sam.py --input Cluster/polished.hq.fasta.gz \
>    -s Aligned/hq_isoforms.fasta.sorted.sam --dun-merge-5-shorter -o collapsed_isoforms.fasta
Traceback (most recent call last):
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==8.7.4', 'collapse_isoforms_by_sam.py')
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/cupcake-8.7.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 240, in <module>
    main(args)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/cupcake-8.7.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 169, in main
    check_ids_unique(args.input, is_fq=args.fq)
  File "/gpfs/ts0/home/ejh243/.conda/envs/isoseq/lib/python2.7/site-packages/cupcake-8.7.4-py2.7-linux-x86_64.egg/cupcake/tofu/utils.py", line 13, in check_ids_unique
    raise Exception, "Duplicate id {0} detected. Abort!".format(r.id)
Exception: Duplicate id Ù detected. Abort!

**Comment by ejh243** [comment]
You were right, I was using a zipped file. I will close this issue. Thanks for you help!
