### ISSUE TITLE
KeyError on collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by alissawilliams** [Magdoll/cDNA_Cupcake#108]
Hello-

I am processing some IsoSeq data according to this tutorial: https://github.com/Magdoll/Cogent/wiki/Tutorial:-Using-Cogent-to-collapse-redundant-transcripts-in-absence-of-genome

I am currently running the commands:
```
collapse_isoforms_by_sam.py --input polished.hq.fastq -s polished.hq.fasta.sorted.sam -c 0.95 -i 0.85 --dun-merge-5-shorter -o polished.hq.fastq.no5merge

get_abundance_post_collapse.py polished.hq.fastq.no5merge.collapsed cluster_report.csv

filter_away_subset.py polished.hq.fastq.no5merge.collapsed
```
but the job fails with a KeyError:
```
Traceback (most recent call last):
  File "/opt/software/miniconda2/envs/anaCogent/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==8.7.1', 'collapse_isoforms_by_sam.py')
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-8.7.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 240, in <module>
    main(args)
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-8.7.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 185, in main
    for recs in iter: # recs is {'+': list of list of records, '-': list of list of records}
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-8.7.1-py2.7-linux-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 81, in iter_gmap_sam
    records = [next(quality_alignments)]
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-8.7.1-py2.7-linux-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 105, in get_quality_alignments
    for r in gmap_sam_reader:
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-8.7.1-py2.7-linux-x86_64.egg/cupcake/io/BioReaders.py", line 453, in next
    return GMAPSAMRecord(line, self.ref_len_dict, self.query_len_dict)
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-8.7.1-py2.7-linux-x86_64.egg/cupcake/io/BioReaders.py", line 183, in __init__
    self.process(record_line, ref_len_dict, query_len_dict)
  File "/opt/software/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-8.7.1-py2.7-linux-x86_64.egg/cupcake/io/BioReaders.py", line 516, in process
    self.qLen = query_len_dict[self.qID]
KeyError: 'transcript/660'
```
Has anyone run into this issue before? transcript/660 is not the first transcript listed in either the sorted sam or the fastq file, and in both appears to be normal.

Thanks,
Alissa

**Comment by alissawilliams** [comment]
Update: I tried re-running the commands with the transcript/660 sequence deleted from the fastq and sam files, but still got the same error, just for transcript/840 this time. So I imagine the issue isn't with an individual sequence, but rather with the underlying creation of the dictionary?

**Comment by alissawilliams** [comment]
I figured out the issue! Based on https://github.com/Magdoll/cDNA_Cupcake/issues/64, I found that I needed to include the flag --fq in the collapse_isoforms_by_sam.py command.

Thanks for all of your work on tools for analyzing Iso-Seq data!

Alissa
