### ISSUE TITLE
demux_by_barcode_groups.py

### ISSUE THREAD

**Issue by BeatrizdeToledo** [Magdoll/cDNA_Cupcake#113]
Good night!
I am having troubles in understanding at which moment I should demultiplex my samples.
As I could understand  the script python demux_by_barcode_groups.py requires the “collapse_isoforms.gff” file, which I am supposed to generate from my iso-seq data.
Is not the gff annotation file available online, right?
Therefore I need to align, collapse my iso-sq samples and only after demultiplex? 
Thank you!!!

**Comment by Magdoll** [comment]
Hi @BeatrizdeToledo ,

Yes. However if you already ran "IsoSeq" protocol in SMRT Link with genome supplied it will already run the collapse step for you. Otherwise you can run collapse on your own.

Yes, the order is:

1. Align HQ transcripts to genome
2. Run [collapse script](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#collapse)
3. Generate [count file](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#count) (not demux yet, just the total FL count per isoform)
4. Optional, [filter away 5' degraded](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#filtersubset) - if you ran collapse with `--no-5-merge`. I usually recommend this combination.
5. Run the demux script

-Liz

**Comment by BeatrizdeToledo** [comment]
Good afternoon,

I just want to confirm something.


I aligned HQ transcripts to genome, then I used TAMA Collapse because I have cap-selected samples.


So next I run get_abundance_post_collapse.py and only then demux_by_barcode_groups.py


I don't need to run demux_isoseq_with_genome.py  or demux_isoseq_no_genome.py, right?

Thanks!


________________________________

**Comment by Magdoll** [comment]
You will need to run demux_isoseq_with_genome.py
because you need the demux counts to then run demux_by_barcode_groups.py

-Liz

**Comment by BeatrizdeToledo** [comment]
but I still need to run get_abundance_post_collapse.py before

demux_isoseq_with_genome.py ?

________________________________

**Comment by Magdoll** [comment]
Yes you do because you need the .read_stats.txt. file that
get_abundance_post_collapse.py generates

https://github.com/Magdoll/cDNA_Cupcake/wiki/Tutorial:-Demultiplexing-SMRT-Link-Iso-Seq-Jobs#mapped

**Comment by BeatrizdeToledo** [comment]
Good evening again! 
I am having some issues during the running of the demux scritpt.

My samples were 5'cap selected, I did the alignment with both GMAP and deSALT for comparison.
Then I did the Collapsing with both collapse_isoforms_by_sam.py and with tama_collapse.py. both work but when I reach the demux_isoseq_with_genome.py step for collapse_isoforms_by_sam.py output I get this:

Reading highquality_desalt_CCS_O224M4_sort.fastq....
Traceback (most recent call last):
  File "demux_isoseq_with_genome.py", line 126, in <module>
    main(args.job_dir, args.mapped_fafq, args.read_stat, args.classify_csv, args.output, primer_names)
  File "demux_isoseq_with_genome.py", line 96, in main
    raise Exception("Expected ID format PB.X.Y but found {0}!".format(r.id))
Exception: Expected ID format PB.X.Y but found UnnamedSample_HQ_transcript/132038!

if I look to the high quality fasta file and the aligned fastq file both are named like this
-bash-4.1$ head -n 1 hq_transcripts.fasta
  UnnamedSample_HQ_transcript/0

-bash-4.1$ head -n 1 highquality_desalt_CCS_O224M4_sort.fastq 
@UnnamedSample_HQ_transcript/132038

while the cluster file is named differently
$ head unpolished.cluster_report.csv
cluster_id,read_id,read_type
transcript/0,m54345U_200310_133837/123864620/ccs,FL

I had similar problems with the tama collapse, 
Traceback (most recent call last):
File "tama_read_support_collapse_cluster.py", line 148, in
cluster_read_list = list(cluster_read_dict[cluster_id].keys())
KeyError: 'UnnamedSample_HQ_transcript'

and Richard replied that 
"However, I noticed that the ID's in your "highquality_gmapn1_collapse_capped_trans_read.bed" file do not match the ID's in your "unpolished.cluster_report.csv".. So the inputs you used will not work since they need to have ID relationships."

The first part of the processing was performed by the facility.
SMRT link version 8.0.0.80529. 
That's the email the facility sent me,

"the first step of the analysis was the CCS run
You got the
CCS report and the
m5434U_200310_133837.Q20.fastq file

There additional files from the CCS run available:
File                                                                 Size         Type
m54345U_200310_133837.Q10.fasta   13 GB     Fasta
m54345U_200310_133837.Q20.fasta   12 GB     Fasta
m54345U_200310_133837.ccs.bam       9 GB     ConsensusReadBamFile
L49711-Cell1 (CCS)                                     34 KB     ConsensusReadSet
m54345U_200310_133837.Q10.fastq   26 GB     Fastq
m54345U_200310_133837.Q20.fastq   23 GB     Fastq
CCS Per-Read Details                                 25 MB     zip
Analysis Log                                                  181 KB   log
SMRT Link Log                                              8 KB        log


With the CCS data set the Isoseq Analysis was done.
You got the
Isoseq analysis report,
Full length non concatemer reads bam file     and the
High quality isoforms fasta file.

Further files are available:
File                                                             Size Type
Full-length Non-Concatemer Report   231 MB csv
Low-Quality Isoforms                             4 MB Fasta
Cluster Report                                         149 MB csv
Full-Length Non-Concatemer Reads   7 GB bam
Isoform Counts by Barcode                   5 MB csv
High-Quality Isoforms                           708 MB Fasta
Analysis Log                                            36 KB log
SMRT Link Log                                          6 KB log
"
Then the High quality isoforms fasta file was mapped to the genome


Do you have any suggestion of how I could fix this problem?
Thank you!
