### ISSUE TITLE
getting RuntimeError while running  collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by archana433** [Magdoll/cDNA_Cupcake#120]
when running cDNA_cupcake-

Traceback (most recent call last):
  File "/home/user/anaconda3/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==11.0.0', 'collapse_isoforms_by_sam.py')
  File "/home/user/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/user/anaconda3/lib/python3.7/site-packages/cupcake-11.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 235, in <module>
    main(args)
  File "/home/user/anaconda3/lib/python3.7/site-packages/cupcake-11.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 169, in main
    check_ids_unique(args.input, is_fq=args.fq)
  File "/home/user/anaconda3/lib/python3.7/site-packages/cupcake-11.0.0-py3.7-linux-x86_64.egg/cupcake/tofu/utils.py", line 11, in check_ids_unique
    for r in SeqIO.parse(open(fa_or_fq_filename), 'fastq' if is_fq else 'fasta'):
  File "/data/applications/BioPython/biopython-1.64/lib64/python2.6/site-packages/Bio/SeqIO/__init__.py", line 586, in parse
    for r in i:
  File "/data/applications/BioPython/biopython-1.64/lib64/python2.6/site-packages/Bio/SeqIO/QualityIO.py", line 1033, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
RuntimeError: generator raised StopIteration

**Comment by Magdoll** [comment]
Hi @archana433 ,
This looks to me like your input fasta/fastq file is corrupt (or you were giving the wrong file format).

What is the full command you were running?

-Liz

**Comment by archana433** [comment]
i was running on cluster- 
this is script - 
~/anaconda3/bin/collapse_isoforms_by_sam.py --input /home/user/data/SRR7652917_subreads.fastq --fq -s $1 --dun-merge-5-shorter -o SRR7652917
command -
qsub -N collapse_isoforms_17  /home/user/data/scripts/cupcake_collapse_isoforms.sh SRR7652917_.sorted.sam

**Comment by Magdoll** [comment]
Hi @archana433 ,

The fastq may be corrupted? Can you try reading it with BioPython? For example try:

```
python <cDNA_Cupcake>/sequence/fq2fa.py SRR7652917_subreads.fastq
```

I notice however that you seem to be processing subreads.fastq data. I highly advise against that. subreads should not be use for direct mapping and collapse. Instead we recommend running through the Iso-Seq bioinformatics pipeline to get CCS (HiFi) reads and through the rest of the steps (classify to get full-length reads, clustering to get high-quality isoform consensus sequences). What was the purpose of this analysis?

-Liz

**Comment by archana433** [comment]
thanks
