### ISSUE TITLE
collapse_isoforms_by_sam ValueError: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by markopetek** [Magdoll/cDNA_Cupcake#14]
I've mapped the hq pacbio sequences to genome using gmap (latest version), sorted the sam file using samtools and then run the collapse_isoforms_by_sam.py script in the anaconda environment (operating system Ubuntu 14.04-biolinux). The script works for few seconds and then crashes with the following error message:

```
...
merged 1 down to 1 transcripts
alt. junction found at 15
alt. junction found at 285
alt. junction found at 577
alt. junction found at 926
alt. junction found at 1333
alt. junction found at 2473
alt. junction found at 3396
alt. junction found at 3611
alt. junction found at 4065
alt. junction found at 4244
alt. junction found at 4988
alt. junction found at 5216
alt. junction found at 5720
alt. junction found at 5970
alt. junction found at 6806
alt. junction found at 7161
merged 2 down to 1 transcripts
Traceback (most recent call last):
  File "/home/adminuser/Documents/MarkoP/potato_pacbio/anaconda2/envs/anaCogent/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==3.1', 'collapse_isoforms_by_sam.py')
  File "/home/adminuser/Documents/MarkoP/potato_pacbio/anaconda2/envs/anaCogent/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/adminuser/Documents/MarkoP/potato_pacbio/anaconda2/envs/anaCogent/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/home/adminuser/Documents/MarkoP/potato_pacbio/anaconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-3.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 244, in <module>
    main(args)
  File "/home/adminuser/Documents/MarkoP/potato_pacbio/anaconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-3.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 190, in main
    for recs in iter:
  File "/home/adminuser/Documents/MarkoP/potato_pacbio/anaconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-3.1-py2.7-linux-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 81, in iter_gmap_sam
    ignored_fout.write("{0}\tCoverage {1:.3f} too low.\n".format(r.qID, r.qCoverage))
ValueError: Unknown format code 'f' for object of type 'str'
(anaCogent) adminuser@biolx[S1_allsize] 
```
I've tried to sort the sam file with picard-tools SamSort but get the same error.

I've uploaded the files to dropbox so you can try to reproduce the error (see console_commands.txt for commands used):
https://www.dropbox.com/sh/6n0q61rq62324hi/AAAtdGIH6O3Wyt3FlzYETUVSa?dl=0

**Comment by Magdoll** [comment]
Hi @markopetek ,

Please sort using
`sort -k 3,3 -k 4,4n all_sizes.quivered_hq_MPE_S1.fastq.sam > all_sizes.quivered_hq_MPE_S1.fastq.sorted.sam` instead.

This way, all unmapped alignments will occur before the mapped alignments. The error message  comes from it expecting all unmapped alignments to have been seen already.

Another way is to simply remove unmapped reads from the SAM file using `samtools view -F 4` (see here: https://groups.google.com/forum/#!msg/smrt_isoseq/zssNwq0aA4c/9UqOU4V0DQAJ)

**Comment by markopetek** [comment]
OK, now it works :+1: . Seems like I had a typo when I first copied this command to the console and it returned an error. I thought then it has to be a samtools sort since I've done it so many times before :smile: 
Thanks for help.
