### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by tay45** [Magdoll/cDNA_Cupcake#182]
Hello,

The python requirement in cDNA Cupcake is Python >= 3.7. But, it is only working in python 2.

thkang@ppxhpcnode19$ module load cDNA_Cupcake
thkang@ppxhpcnode19$ python --version
Python 3.7.11
thkang@ppxhpcnode19$ fusion_finder.py --input clustered.hq.fasta -s aligned.sorted.sam -o aligned.sorted.sam.fusion --cluster_report_csv clustered.cluster_report.csv
Traceback (most recent call last):
  File "/opt/cDNA_Cupcake/bin/fusion_finder.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==28.0.0', 'fusion_finder.py')
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 402, in <module>
    is_flnc=args.is_flnc)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 286, in fusion_main
    fusion_candidates = find_fusion_candidates(sam_filename, bs.transfrag_len_dict, min_locus_coverage, min_locus_coverage_bp, min_total_coverage, min_dist_between_loci, min_identity=min_identity)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 251, in find_fusion_candidates
    all(a.iden>=min_identity for a in data) and \
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 251, in <genexpr>
    all(a.iden>=min_identity for a in data) and \
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
thkang@ppxhpcnode19$ 

--------------------------------------------------------------

thkang@ppxhpcnode19$ module load Python/2.7.14
thkang@ppxhpcnode19$ python --version
Python 2.7.14
thkang@ppxhpcnode19$ fusion_finder.py --input clustered.hq.fasta -s aligned.sorted.sam -o aligned.sorted.sam.fusion --cluster_report_csv clustered.cluster_report.csv 
0 fusion candidates identified.
Output written to: aligned.sorted.sam.fusion.gff, aligned.sorted.sam.fusion.group.txt, aligned.sorted.sam.fusion.rep.fa
WARNING: isoseq3 format detected. Output `length` column will be `NA`.
.
.
.
Read stat file written to aligned.sorted.sam.fusion.read_stat.txt
Abundance file written to aligned.sorted.sam.fusion.abundance.txt
Count information written to: aligned.sorted.sam.fusion.abundance.txt

It looks I download the correct version (28.0.0). Is there a way to run it on the python 3? 

Thank you!

**Comment by Magdoll** [comment]
This doesn't look like a Python version issue. The error from the first fusion finding looks to be a genuine error from processing the files. If this is still an issue, please open the issue again.

**Comment by tay45** [comment]
Hello,

I have reopened this issue (#193) because I couldn't resolve the problem.
Thank you!

2022년 2월 5일 (토) 오전 9:31, Elizabeth Tseng ***@***.***>님이 작성:
