### ISSUE TITLE
collapse_isoforms_by_sam.py No module named 'cupcake.tofu.branch.c_branch'

### ISSUE THREAD

**Issue by kechalar-hua** [Magdoll/cDNA_Cupcake#185]
collapse_isoforms_by_sam.py -h

Traceback (most recent call last):
  File "/public/home/zjh/miniconda3/envs/anaCogent/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==28.0.0', 'collapse_isoforms_by_sam.py')
  File "/public/home/zjh/miniconda3/envs/anaCogent/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/home/zjh/miniconda3/envs/anaCogent/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/public/home/zjh/2.my_software/cDNA_Cupcake/cupcake.egg-info/scripts/collapse_isoforms_by_sam.py", line 31, in <module>
    from cupcake.tofu.branch import branch_simple2
  File "/public/home/zjh/2.my_software/cDNA_Cupcake/cupcake/tofu/branch/branch_simple2.py", line 6, in <module>
    import cupcake.tofu.branch.c_branch as c_branch
ModuleNotFoundError: No module named 'cupcake.tofu.branch.c_branch'

my ~/.bashrc:
export PATH="/public/home/zjh/2.my_software/cDNA_Cupcake/sequence:$PATH"
export PATH="/public/home/zjh/2.my_software/mash-Linux64-v2.3:$PATH"
export PYTHONPATH=/public/home/zjh/2.my_software/cDNA_Cupcake/:$PYTHONPATH

**Comment by kechalar-hua** [comment]
solved.
rm -f cDNA-cupcake then it is useful.
