### ISSUE TITLE
ISSUE: fusion_finder.py

### ISSUE THREAD

**Issue by tay45** [Magdoll/cDNA_Cupcake#193]
Hello,

I reopen the issue for the fusion_finder.py instead of the closed #182.

Previously, I suspected that the issue might be due to the python version.

But, I think that you have had a different idea. Could you please help me to resolve this problem.

According to your suggestion, I have run the script again in the python 3. But, I have gotten the same error as below.

Thank you for the help!

-------------------------------------------------------------------------------------------------

thkang@ppxhpcnode11$ module load cDNA_Cupcake
thkang@ppxhpcnode11$ python --version
Python 3.7.11
thkang@ppxhpcnode11$ fusion_finder.py --input clustered.hq.fasta -s aligned.sorted.sam -o aligned.sorted.sam.fusion
Traceback (most recent call last):
  File "/opt/cDNA_Cupcake/bin/fusion_finder.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==28.0.0', 'fusion_finder.py')
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 402, in <module>
    is_flnc=args.is_flnc)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 286, in fusion_main
    fusion_candidates = find_fusion_candidates(sam_filename, bs.transfrag_len_dict, min_locus_coverage, min_locus_coverage_bp, min_total_coverage, min_dist_between_loci, min_identity=min_identity)
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 251, in find_fusion_candidates
    all(a.iden>=min_identity for a in data) and \
  File "/opt/cDNA_Cupcake/lib/python3.7/site-packages/cupcake-28.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 251, in <genexpr>
    all(a.iden>=min_identity for a in data) and \
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
thkang@ppxhpcnode11$

**Comment by tay45** [comment]
Hello,

I have confirmed that this error isn't due to the python version.

The module (module load Python/2.7.14), what I loaded on our server to switch the python version, contained the former version of the cDNA-Cupcake. 

So, I did actually run the former version of the fusion_finder.py instead of the current version. I am sorry for my mistake.

Regarding the error of the current version of the fusion_finder.py, I have resolved the problem.

On the command line of the fusion_finder.py, I put the sam file converted from the aligned.bam file produced by the pbmm2 with the --sort option.

(pbmm2 align clustered_bam reference out --preset ISOSEQ --sort)

But, it didn't work.

So, this time, I have used the sorted.sam file from the minimap2 alignment.

(minimap2 -ax splice -t 30 -uf --secondary=no -C5 \
   hg38.fa hq_isoforms.fastq > hq_isoforms.fastq.sam

sort -k 3,3 -k 4,4n hq_isoforms.fastq.sam > hq_isoforms.fastq.sorted.sam)

And, it is working well now.
