### ISSUE TITLE
pkg_resources.ResolutionError when running "collapse_isoforms_by_sam.py"

### ISSUE THREAD

**Issue by ssaif-cellarity** [Magdoll/cDNA_Cupcake#220]
`collapse_isoforms_by_sam.py --input HL60_fltnc_dedup.fasta -s HL60_fltnc_dedup.fasta.sorted.sam -c 0.99 -i 0.95 --gen_mol_count -o HL60_fltnc_dedup.5merge &`
[1] 41376
(SQANTI3.env) [/home/ubuntu/Yale_PacBio_Data/isoseq_single-cell_analysis] Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/SQANTI3.env/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==28.0.0', 'collapse_isoforms_by_sam.py')
  File "/home/ubuntu/miniconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ubuntu/miniconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/collapse_isoforms_by_sam.py' not found in metadata at '/home/ubuntu/cDNA_Cupcake/cupcake.egg-info'

**Comment by ssaif-cellarity** [comment]
`echo $PYTHONPATH`
/home/ubuntu/cDNA_Cupcake/sequence/:/home/ubuntu/cDNA_Cupcake/sequence/:/home/ubuntu/cDNA_Cupcake/sequence/:/home/ubuntu/cDNA_Cupcake/

`echo $PATH`
/home/ubuntu/miniconda3/envs/SQANTI3.env/bin:/home/ubuntu/bioinfo/STAR-2.7.0a/bin/Linux_x86_64:/home/ubuntu/bioinfo/cellranger-3.1.0:/home/ubuntu/.local/bin:/home/ubuntu/miniconda3/bin:/home/ubuntu/miniconda3/condabin:/home/ubuntu/cDNA_Cupcake/sequence:/home/ubuntu/cDNA_Cupcake/rarefaction

`which collapse_isoforms_by_sam.py`
/home/ubuntu/miniconda3/envs/SQANTI3.env/bin/collapse_isoforms_by_sam.py

**Comment by wx904** [comment]
I had the same issue after running the python script `sqanti3.py`. When I went back to rerun `collapse_isoforms_by_sam.py`, the same "pkg_resources.ResolutionError..." error occurred, and same to other cupcake programs.
