### ISSUE TITLE
fusion_finder.py error

### ISSUE THREAD

**Issue by Trandamere** [Magdoll/cDNA_Cupcake#24]
what's wrong with this?
```
gmap -D /disk/luping/bam/iso-bam/all-cluster/evaluate_tofu2 -d FG -f samse -n 0 -t 13 -z sense_force consensus.fasta >consensus.fasta.sam
sort -k 3,3 -k 4,4n consensus.fasta.sam >consensus.fasta.sort.sam
```

```
[luping@centos pb-con-check]$ fusion_finder.py --input consensus.fasta -s consensus.fasta.sort.sam -o ./fusion
Traceback (most recent call last):
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/bin/fusion_finder.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==3.0', 'fusion_finder.py')
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/cupcake-3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 393, in <module>
    min_dist_between_loci=args.min_dist_between_loci)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/cupcake-3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 301, in fusion_main
    o = merge_fusion_exons(v, max_fusion_point_dist=100, max_exon_end_dist=0, allow_extra_5_exons=allow_extra_5_exons)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/cupcake-3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 207, in merge_fusion_exons
    if all(is_fusion_compatible(r1, r2, max_fusion_point_dist, max_exon_end_dist, allow_extra_5_exons) for r2 in r2s):
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/cupcake-3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 207, in <genexpr>
    if all(is_fusion_compatible(r1, r2, max_fusion_point_dist, max_exon_end_dist, allow_extra_5_exons) for r2 in r2s):
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/cupcake-3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 153, in is_fusion_compatible
    type = compare_junctions(r1, r2)
  File "/disk/luping/tools/third-seq/pitchfork-isoseq_sa5.0.0/lib/python2.7/site-packages/cupcake-3.0-py2.7-linux-x86_64.egg/cupcake/tofu/compare_junctions.py", line 21, in compare_junctions
    strand = r1.strand
AttributeError: GMAPSAMRecord instance has no attribute 'strand'
```

**Comment by Trandamere** [comment]
I already solved it!
