### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by Journeyant** [Magdoll/cDNA_Cupcake#245]
Hi, Magdoll,
    After I installed the cDNA_cupcake, I ran the "collapse_isoforms_by_sam.py", but I'm getting the following error:

Traceback (most recent call last):
  File ".../SQANTI3_v5.2/cDNA_Cupcake/cDNA_Cupcake/cupcake/tofu/./collapse_isoforms_by_sam.py", line 31, in <module>
    from cupcake.tofu.branch import branch_simple2
  File ".../anaconda3/envs/SQANTI3-5.2/lib/python3.10/site-packages/cupcake/tofu/branch/branch_simple2.py", line 6, in <module>
    import cupcake.tofu.branch.c_branch as c_branch
  File "cupcake/tofu/branch/c_branch.pyx", line 6, in init cupcake.tofu.branch.c_branch
  File ".../anaconda3/envs/SQANTI3-5.2/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

What should I do?
It would be very helpful if you could help me with this problem. Thank you. @Magdoll 
Journeyant

**Comment by tky199996** [comment]
I encountered the same problem as you，Have you solved this problem?

**Comment by Magdoll** [comment]
Hi @tky199996  - Cupcake is no longer supported. See my other comments.
