### ISSUE TITLE
fusion_finder.py assertion

### ISSUE THREAD

**Issue by thelingxichen** [Magdoll/cDNA_Cupcake#37]
Hi,

First, I used minimap2 to get the hq_isoforms.sam, then run fusion_finder.py with:

```
fusion_finder.py \                                                                                
    --input $fastq --fq \
    -s $sam \
    --dun-merge-5-shorter \
    -o $out_fn \
    --cluster_report_csv $report
```
while I got the error:
```
combo seen: (58, 59)
combo seen: (9, 10)
combo seen: (29, 30)
combo seen: (9, 10)
combo seen: (4, 8)
combo seen: (18, 19)
Traceback (most recent call last):
  File "/home/chenlingxi/mnt/chenlingxi/lib/tools/anaconda2/bin/fusion_finder.py", line 395, in <module>
    min_dist_between_loci=args.min_dist_between_loci)
  File "/home/chenlingxi/mnt/chenlingxi/lib/tools/anaconda2/bin/fusion_finder.py", line 347, in fusion_main
    assert pbid1.split('.')[1] == pbid2.split('.')[1]
AssertionError
```

How can I fix this? Thanks.

**Comment by paprikachan** [comment]
I used tofu2_v21

**Comment by Magdoll** [comment]
Hi @paprikachan,

Can you update to the latest Cupcake version (also tagged as `cupcake_v5.8`) ? I've updated that section of code in `fusion_finder.py` so I want to see if the new version fixes it.

**Comment by paprikachan** [comment]
v5.8 works. Thanks.
