### ISSUE TITLE
Invalid cluster_id for abundance script

### ISSUE THREAD

**Issue by SziKayLeung** [Magdoll/cDNA_Cupcake#42]
Hello @Magdoll, 
Hope you are well. 

I'm currently experiencing some challenges obtaining count information using get_abundance_post_collapse.py script after Isoseq3 due to errors with clusterID: 

get_abundance_post_collapse.py ./Collapse_Isoform/Q21.collapsed cluster_report.csv
Traceback (most recent call last):
  File "/usr/bin/get_abundance_post_collapse.py", line 5, in <module>
    pkg_resources.run_script('cupcake==5.2', 'get_abundance_post_collapse.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/cupcake-5.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 435, in <module>
    get_abundance_post_collapse(args.collapse_prefix, args.cluster_report, args.collapse_prefix)
  File "/usr/lib64/python2.7/site-packages/cupcake-5.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 422, in get_abundance_post_collapse
    output_read_count_IsoSeq_csv(cid_info, cluster_report_csv, output_prefix + '.read_stat.txt')
  File "/usr/lib64/python2.7/site-packages/cupcake-5.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 148, in output_read_count_IsoSeq_csv
    raise Exception, "cluster_id {0} is not a valid cluster ID!".format(cid)
Exception: cluster_id transcript/0 is not a valid cluster ID!

However, the cluster report appears to be correct as outlined in the Isoseq3 github page: 
cluster_id,read_id,read_type
transcript/0,m54082_180607_173058/60883723/ccs,FL
transcript/0,m54082_180607_173058/6161326/ccs,FL
transcript/0,m54082_180607_173058/27460031/ccs,FL
transcript/1,m54082_180607_173058/24838457/ccs,FL

I did also try modifiying the collapsed result and cluster_report.csv, however given there were no prefix and cid needs formatting, I wasn't able to proceed further. 

As a side note, I also did have errors when generating the cluster report itself with the isoseq3_make_cluster_report.py with polished.bam file: 
Traceback (most recent call last):
  File "/mnt/data1/software/PacBio/cDNA_Cupcake/post_isoseq_cluster/isoseq3_make_cluster_report.py", line 35, in <module>
    make_cluster_report_from_polished_bam(args.polished_bam)
  File "/mnt/data1/software/PacBio/cDNA_Cupcake/post_isoseq_cluster/isoseq3_make_cluster_report.py", line 9, in make_cluster_report_from_polished_bam
    f = pysam.Samfile(polished_bam)
  File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 664, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
However, this was resolved when I edited the script with "f = pysam.Samfile(polished_bam,check_sq=False)" 
- wondering whether this has been observed before, or whether this suggests that there are problems with my original polished.bam file

Any help will be greatly appreciated. Thank you so much!

**Comment by Magdoll** [comment]
Hi,
Please try the latest Cupcake version that i just pushed in. It should recognize the Iso-Seq3 ID formats now. If not, let me know and I can help make sure the formats work.

--Liz

**Comment by SziKayLeung** [comment]
Hello Liz, 

Sorry for the late reply but thank you so much for updating the scripts. The formats worked, and the abundance.txt and group.stat.txt outputs are as expected :)

However, during the run, I received loads of warnings "WARNING: isoseq3 format detected. Output `length` column will be `NA`." (specifically, 179,600 of these lines, with no other information). 

I don't recall this happening with Isoseq2(beta) on smrtlink. So just wanted to check with you if this is something that I should be expecting with Isoseq3, and what are reads that are giving NA length.

Thank you, 
Szi Kay

**Comment by Magdoll** [comment]
Hi @SziKayLeung ,

That warning was intentionally added in the last Cupcake update. This is because older versions of the FL CCS id format allowed extraction of sequence lengths. The ID format in Iso-Seq1 and 2 used to be `<movie>/<zmw>/<start>_<end>_CCS` but now in Iso-Seq 3 it is `<movie>/<zmw>/ccs` and the length information is not contained in the ID. It's a minor matter but to kept compatibility I'm still outputting the `length` field, but you'll find them `NA` when running on Iso-Seq 3 runs.

--Liz

**Comment by SziKayLeung** [comment]
Thank you @Magdoll for clarifying!
