### ISSUE TITLE
Value_error

### ISSUE THREAD

**Issue by joonlee311** [Magdoll/cDNA_Cupcake#43]
Hi,

I got this error message after running "collapse_isoforms_by_sam.py".
Could you please let me know what needs to be done here?

Thanks.

Traceback (most recent call last):
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==5.8', 'collapse_isoforms_by_sam.py')
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-5.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 245, in <module>
    main(args)
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-5.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 204, in main
    collapse_fuzzy_junctions(f_good.name, f_txt.name, args.allow_extra_5exon, internal_fuzzy_max_dist=args.max_fuzzy_junction)
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-5.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 149, in collapse_fuzzy_junctions
    _size = get_fl_from_id(group_info[pbid])
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-5.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 92, in get_fl_from_id
    return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
  File "/home/joonlee3/bin/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-5.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 92, in <genexpr>
    return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
ValueError: invalid literal for int() with base 10: '714.1'

**Comment by Magdoll** [comment]
Hi @joonlee311 ,
This is definitely caused by an ID format that was not expected. The error comes from expecting the ID to have the format:

```
XXXXXX/f<int>p<int>/<length>
```

Are you running Iso-Seq3? This looks like an edge case I had not accounted for for newer ID formats. I pushed a new version of Cupcake (v5.9) to the repo just now that should take care of this. If not, please let me know.

--Liz
