### ISSUE TITLE
get_abundance_post_collapse.py seems not compliant with isoseq3 format

### ISSUE THREAD

**Issue by jcleple33** [Magdoll/cDNA_Cupcake#46]
Running the isoseq3 suite provide me "cluster_report.csv file" on this format :

cluster_id,read_id,read_type
transcript/11530,m54064_180112_100315/68092545/ccs,FL
transcript/11530,m54064_180112_100315/35979778/ccs,FL
transcript/11530,m54064_180112_100315/20448150/ccs,FL

and « collapsed.group.txt" on this format :

PB.1.1	transcript/1968,transcript/2407,transcript/3021,transcript/3170,transcript/5415
PB.1.2	transcript/22838
PB.2.1	transcript/3489,transcript/3803

Now running the get_abundance_post_collapse.py give meh this error message

$ srun get_abundance_post_collapse.py hq_isoforms.fasta.no5merge.collapsed /home/jleple/work/Isoseq3_CO1_ccs/POLISH9999/cluster_report.csv
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-v3.6_env/bin/get_abundance_post_collapse.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==5.3', 'get_abundance_post_collapse.py')
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-v3.6_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-v3.6_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-v3.6_env/lib/python2.7/site-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 435, in <module>
    get_abundance_post_collapse(args.collapse_prefix, args.cluster_report, args.collapse_prefix)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-v3.6_env/lib/python2.7/site-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 422, in get_abundance_post_collapse
    output_read_count_IsoSeq_csv(cid_info, cluster_report_csv, output_prefix + '.read_stat.txt')
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-v3.6_env/lib/python2.7/site-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 148, in output_read_count_IsoSeq_csv
    raise Exception, "cluster_id {0} is not a valid cluster ID!".format(cid)
Exception: cluster_id transcript/0 is not a valid cluster ID!
srun: error: node130: task 0: Exited with exit code 1

Have you a solution for me?

Thank you very much in advance

Jean-Charles

**Comment by Magdoll** [comment]
Hi @jcleple33 ,

Later versions of Cupcake (v5.9 and the latest v.5.10 I just updated) will handle the IsoSeq3 format. If error still persists, please post the error again.

Thanks,
--Liz
