### ISSUE TITLE
Error when running get_abundance_post_collapse.py

### ISSUE THREAD

**Issue by rnett42** [Magdoll/cDNA_Cupcake#48]
I am in the process of running through the cupcake/tofu pipeline (following cogent) to remove redundant transcripts (in the absence of genomes), and I've gotten hung up at the get_abundance_post_collapse.py step. The script I used is as follows:

`get_abundance_post_collapse.py hq_isoforms.fasta.no5merge.collapsed cluster_report.csv
`
My job fails with the following output:

Traceback (most recent call last):
  File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/cdna_cupcake_20180921/bin/get_abundance_post_collapse.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==5.9', 'get_abundance_post_collapse.py')
  File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/cdna_cupcake_20180921/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/cdna_cupcake_20180921/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/cdna_cupcake_20180921/lib/python2.7/site-packages/cupcake-5.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 319, in <module>
    get_abundance_post_collapse(args.collapse_prefix, args.cluster_report, args.collapse_prefix)
  File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/cdna_cupcake_20180921/lib/python2.7/site-packages/cupcake-5.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 306, in get_abundance_post_collapse
    output_read_count_IsoSeq_csv(cid_info, cluster_report_csv, output_prefix + '.read_stat.txt')
  File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/cdna_cupcake_20180921/lib/python2.7/site-packages/cupcake-5.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 177, in output_read_count_IsoSeq_csv
    id=x, len=get_roi_len(x), is_fl='Y', stat=stat, pbid=pbid))
  File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/cdna_cupcake_20180921/lib/python2.7/site-packages/cupcake-5.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 50, in get_roi_len
    s, e, junk = seqid.split('/')[2].split('_')
ValueError: need more than 1 value to unpack

I'm guessing that this is likely something very simple that I've done incorrectly, but I seem to have exhausted the extent of my troubleshooting potential for this (I think). Please let me know if you've run into this before!

Thanks,
Ryan

**Comment by Magdoll** [comment]
Hi @rnett42 ,

This just means it is expecting the FL reads to have one of the following formats and it doesn't see them. It should either be:

```
<movie>/<zmw>/<start>_<end>_CCS
```

or

```
<movie>/<zmw>/ccs
```

Take a look at the read IDs in `cluster_report.csv` and tell me what you see.

--Liz

**Comment by Magdoll** [comment]
Hmm, that looks pretty good to me. Do you mind emailing me the following files for me to do a quick test?

- cluster_report.csv
- all files starting with hq_isoforms.fasta.no5merge.collapsed.

to etseng@pacb.com.

Thx!

**Comment by Magdoll** [comment]
Good to hear!
