### ISSUE TITLE
summarize_sample_GFF_junctions does not work without genome filename

### ISSUE THREAD

**Issue by brielin** [Magdoll/cDNA_Cupcake#50]
Running summarize_sample_GFF_junctions without GENOME_FILENAME results in the following error:

Traceback (most recent call last):
  File "/usr/local/bin/summarize_sample_GFF_junctions.py", line 5, in <module>
    pkg_resources.run_script('cupcake==6.1', 'summarize_sample_GFF_junctions.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cupcake-6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/summarize_sample_GFF_junctions.py", line 179, in <module>
    print >> sys.stder, "No genome file given. Ignore."
AttributeError: 'module' object has no attribute 'stder'

Looks like a basic typo.

**Comment by Magdoll** [comment]
Typo Fixed in v6.3.
