### ISSUE TITLE
scrub_sample_GFF_junctions errors while parsing bed from summarize step

### ISSUE THREAD

**Issue by brielin** [Magdoll/cDNA_Cupcake#51]
Running

scrub_sample_GFF_junctions.py --scrubbed_junction_file "${summary_prefix}.junction.bed" "${scrub_config}" "${summary_prefix}.junction_detail.txt" "${scrub_prefix}" 

Results in the following error
Traceback (most recent call last):
  File "/usr/local/bin/scrub_sample_GFF_junctions.py", line 5, in <module>
    pkg_resources.run_script('cupcake==6.1', 'scrub_sample_GFF_junctions.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cupcake-6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/scrub_sample_GFF_junctions.py", line 279, in <module>
    tree = read_scrubbed_junction_to_tree(output_filename)
  File "/usr/local/lib/python2.7/dist-packages/cupcake-6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/scrub_sample_GFF_junctions.py", line 112, in read_scrubbed_junction_to_tree
    chrom, left, right, strand = line.strip().split('\t')
ValueError: need more than 1 value to unpack

Indeed, the BED file produced by the summary step has 6 columns. Here are the first few lines

track name=junctions description="summary" useScore=1
chr1    1013575 1013984 summary 3       +
chr1    1803416 1803876 summary 1       +
chr1    2391957 2395784 summary 3       +

**Comment by Magdoll** [comment]
This should be fixed in v6.4. I also updated the test data.
