### ISSUE TITLE
CupCake error duplicate ID

### ISSUE THREAD

**Issue by manyasi06** [Magdoll/cDNA_Cupcake#54]
I had combined two isoseq cells and got an error for duplicate ids but I didn't find any duplicates in my polished.hq.fasta file.  Where exactly is it finding the duplicate id names.

thanks.

```
Traceback (most recent call last):
  File "/scinet01/gov/usda/ars/scinet/project/tgbs_analysis/anaconda3/envs/TofCogent/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==6.1', 'collapse_isoforms_by_sam.py')
  File "/scinet01/gov/usda/ars/scinet/project/tgbs_analysis/anaconda3/envs/TofCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/scinet01/gov/usda/ars/scinet/project/tgbs_analysis/anaconda3/envs/TofCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/scinet01/gov/usda/ars/scinet/project/tgbs_analysis/anaconda3/envs/TofCogent/lib/python2.7/site-packages/cupcake-6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 248, in <module>
    main(args)
  File "/scinet01/gov/usda/ars/scinet/project/tgbs_analysis/anaconda3/envs/TofCogent/lib/python2.7/site-packages/cupcake-6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 177, in main
    check_ids_unique(args.input, is_fq=args.fq)
  File "/scinet01/gov/usda/ars/scinet/project/tgbs_analysis/anaconda3/envs/TofCogent/lib/python2.7/site-packages/cupcake-6.1-py2.7-linux-x86_64.egg/cupcake/tofu/utils.py", line 13, in check_ids_unique
    raise Exception, "Duplicate id {0} detected. Abort!".format(r.id)
Exception: Duplicate id  detected. Abort
```

**Comment by manyasi06** [comment]
Realized the parse don't like gzipped files.
