### ISSUE TITLE
ValueError: Sequence and quality captions differ.

### ISSUE THREAD

**Issue by ncgrjsmiao** [Magdoll/cDNA_Cupcake#62]
(anaCogent5.2) [jsmiao@node30 subreads_bam]$ collapse_isoforms_by_sam.py --input polished.hq.fasta.gz --fq -s polished.hq.fasta.sorted.sam -o test

Traceback (most recent call last):
  File "/data5/home/jsmiao/anaconda2/envs/anaCogent5.2/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==6.8', 'collapse_isoforms_by_sam.py')
  File "/data5/home/jsmiao/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data5/home/jsmiao/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/data5/home/jsmiao/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-6.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 248, in <module>
    main(args)
  File "/data5/home/jsmiao/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-6.8-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 177, in main
    check_ids_unique(args.input, is_fq=args.fq)
  File "/data5/home/jsmiao/anaconda2/envs/anaCogent5.2/lib/python2.7/site-packages/cupcake-6.8-py2.7-linux-x86_64.egg/cupcake/tofu/utils.py", line 11, in check_ids_unique
    for r in SeqIO.parse(open(fa_or_fq_filename), 'fastq' if is_fq else 'fasta'):
  File "/data5/home/jsmiao/.local/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 582, in parse
    for r in i:
  File "/data5/home/jsmiao/.local/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1033, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/data5/home/jsmiao/.local/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 922, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
ValueError: Sequence and quality captions differ.

**Comment by Magdoll** [comment]
Hi @ncgrjsmiao ,

This is not a Cupcake error. Your FASTQ have records that have differing sequence ID vs quality IDs (see: https://github.com/snayfach/MicrobeCensus/issues/4). Please fix the FASTQ formatting.

--Liz
