### ISSUE TITLE
KeyError raised while runing collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by whappycoffee** [Magdoll/cDNA_Cupcake#64]
Hi,
I met this problem while I was running the collapse_isoforms_by_sam.py program. The program always crash for KeyError, here is the error message:

```
$ collapse_isoforms_by_sam.py --input hq_isoforms1.fasta --fq -s hq_isoforms1.fasta.sorted.sam --dun-merge-5-shorter -o iso 
Traceback (most recent call last):
  File "/Users/wuyibo/anaconda2/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==6.8', 'collapse_isoforms_by_sam.py')
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/cupcake-6.8-py2.7-macosx-10.6-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 248, in <module>
    main(args)
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/cupcake-6.8-py2.7-macosx-10.6-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 193, in main
    for recs in iter: # recs is {'+': list of list of records, '-': list of list of records}
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/cupcake-6.8-py2.7-macosx-10.6-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 81, in iter_gmap_sam
    records = [next(quality_alignments)]
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/cupcake-6.8-py2.7-macosx-10.6-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 98, in get_quality_alignments
    for r in gmap_sam_reader:
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/cupcake-6.8-py2.7-macosx-10.6-x86_64.egg/cupcake/io/BioReaders.py", line 453, in next
    return GMAPSAMRecord(line, self.ref_len_dict, self.query_len_dict)
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/cupcake-6.8-py2.7-macosx-10.6-x86_64.egg/cupcake/io/BioReaders.py", line 183, in __init__
    self.process(record_line, ref_len_dict, query_len_dict)
  File "/Users/wuyibo/anaconda2/lib/python2.7/site-packages/cupcake-6.8-py2.7-macosx-10.6-x86_64.egg/cupcake/io/BioReaders.py", line 516, in process
    self.qLen = query_len_dict[self.qID]
KeyError: 'c23588/f1p0/1606'
```
I looked into my hq_isoforms.fastq file, the "c23588/f1p0/1606" isoform did exist, when I removed this isoform and run it all over again, same error occur with another isoform.

I have run data from several different samples using cupcake, this kind of situation never happened on other dataset, I'm wonder if it is the problem of my data? how can I fix it?

**Comment by bioinformatist** [comment]
You use fasta file as input, so you should not use `--fq` parameter here.

**Comment by whappycoffee** [comment]
Yes, that is, thank you!
