### ISSUE TITLE
get_abundance_post_collapse.py error

### ISSUE THREAD

**Issue by stanikae** [Magdoll/cDNA_Cupcake#72]
I am getting the following error when running get_abundance_post_collapse.py, the transcript it's complaining about seems present in all files ( using grep "transcript/14165" hq_isoforms.fasta.no5merge.collapsed*).

**I am using IsoSeq3 (SMRT Link 6.0.0.47841)**

`Namespace(allow_extra_5exon=False, flnc_coverage=-1, fq=False, input='/home/stanford/tmp/cogent_out/hq_transcripts.fasta', max_3_diff=100, max_5_diff=1000, max_fuzzy_junction=5, min_aln_coverage=0.95, min_aln_identity=0.85, prefix='hq_isoforms.fasta.no5merge', sam='/home/stanford/tmp/cogent_out/downstream-analysis/hq_isoforms.fasta.sorted.sam')
Traceback (most recent call last):
  File "/home/stanford/anaconda3/envs/anaCogent/bin/get_abundance_post_collapse.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==5.3', 'get_abundance_post_collapse.py')
  File "/home/stanford/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/stanford/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/stanford/anaconda3/envs/anaCogent/lib/python2.7/site-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 435, in <module>
    get_abundance_post_collapse(args.collapse_prefix, args.cluster_report, args.collapse_prefix)
  File "/home/stanford/anaconda3/envs/anaCogent/lib/python2.7/site-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 422, in get_abundance_post_collapse
    output_read_count_IsoSeq_csv(cid_info, cluster_report_csv, output_prefix + '.read_stat.txt')
  File "/home/stanford/anaconda3/envs/anaCogent/lib/python2.7/site-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 148, in output_read_count_IsoSeq_csv
    raise Exception, "cluster_id {0} is not a valid cluster ID!".format(cid)
Exception: cluster_id transcript/14165 is not a valid cluster ID!`

My cluster_csv file looks like this:

cluster_id,read_id,read_type
transcript/14165,m54271_190507_211125/71565388/ccs,FL
transcript/14165,m54271_190507_211125/35389566/ccs,FL
transcript/14165,m54271_190507_211125/32703404/ccs,FL
transcript/14165,m54271_190507_211125/12320939/ccs,FL
transcript/14165,m54271_190507_211125/13238571/ccs,FL
transcript/14166,m54271_190507_211125/26936301/ccs,FL
transcript/14166,m54271_190507_211125/11141228/ccs,FL
transcript/14166,m54271_190507_211125/43582428/ccs,FL
transcript/14167,m54271_190507_211125/42730163/ccs,FL

**Comment by stanikae** [comment]
Have just seen that i need to first classify_report.csv and cluster_report.csv using isoseq3_make_classify_report.py and isoseq3_make_cluster_report.py respectively. 

Not sure how i had missed this part of the tutorial...

**Comment by stanikae** [comment]
> Have just seen that i need to first make classify_report.csv and cluster_report.csv using isoseq3_make_classify_report.py and isoseq3_make_cluster_report.py respectively.
> 
> Not sure how i had missed this part of the tutorial...

Just noticed that this brings me back to the same problem. Please help with my initial error.
