### ISSUE TITLE
new question about List index out of range error in collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by zhangxiner2** [Magdoll/cDNA_Cupcake#77]
I use the new versions of Cupcake(7.5),  (And my command line like this: /data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/bin/collapse_isoforms_by_sam.py -c 0.95 -i 0.95 --input Trinity.modified.fasta -s hq_isoforms.fasta.sorted.sam --dun-merge-5-shorter -o test)
 but when running cDNA_cupcake, I'm encountering the following error:

merged 1 down to 1 transcripts
merged 1 down to 1 transcripts
merged 8 down to 2 transcripts
merged 1 down to 1 transcripts
merged 2 down to 1 transcripts
merged 75 down to 12 transcripts
merged 2 down to 1 transcripts
merged 291 down to 15 transcripts
Traceback (most recent call last):
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==7.5', 'collapse_isoforms_by_sam.py')
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py",
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py",
      exec(code, namespace, namespace)
    File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_
      main(args)
    File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_
      collapse_fuzzy_junctions(f_good.name, f_txt.name, args.allow_extra_5exon, internal_fuzzy_max_dist=args.max_fuzzy_j
    File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_
      _size = get_fl_from_id(group_info[pbid])
    File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_
      return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
    File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_
      return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
  IndexError: list index out of range  

As you say, this is usually a sequence ID mis-match issue.And I have changed the transcript id using a Python script you provide in the #13. However, I'm encountering the following error:
Traceback (most recent call last):
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==7.5', 'collapse_isoforms_by_sam.py')
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 248, in <module>
    main(args)
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 193, in main
    for recs in iter: # recs is {'+': list of list of records, '-': list of list of records}
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 81, in iter_gmap_sam
    records = [next(quality_alignments)]
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 105, in get_quality_alignments
    for r in gmap_sam_reader:
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/cupcake/io/BioReaders.py", line 453, in next
    return GMAPSAMRecord(line, self.ref_len_dict, self.query_len_dict)
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/cupcake/io/BioReaders.py", line 183, in __init__
    self.process(record_line, ref_len_dict, query_len_dict)
  File "/data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/cupcake/io/BioReaders.py", line 518, in process
    raise Exception, "Unable to find qID {0} in the input fasta/fastq!".format(self.qID)
Exception: Unable to find qID 8ff45b2b-ad86-461c-b0cd-647061fb44f9|- in the input fasta/fastq!

I think the things goes bad. Because as the start, I can get some of the result as test.collapsed.gff without the finall result, but I can't define it is unbroken. After changing the ID, I can't get anything. Please can you give me some suggestion?

**Comment by Magdoll** [comment]
It still looks like you have weird IDs based on the error message (your IDs look like `8ff45b2b-ad86-461c-b0cd-647061fb44f9`). 

Please make sure that whenever you change IDs, you *have* to change the FASTA and the aligned SAM file too.

**Comment by zhangxiner2** [comment]
Thanks for your reply.
my command line like this: /data/mg1/zhangx/system/bin/miniconda3/envs/python2.7/bin/collapse_isoforms_by_sam.py -c 0.95 -i 0.95 --input Trinity.modified.fasta -s hq_isoforms.fasta.sorted.sam --dun-merge-5-shorter -o test

I changed the ID of Trinity.modified.fasta, but didn't change the hq_isoforms.fasta.sorted.sam. Maybe I should change the ID before developing the sam. I will try it again.

**Comment by Magdoll** [comment]
Closed until further notice.
