### ISSUE TITLE
Error in running test data

### ISSUE THREAD

**Issue by psur9757** [Magdoll/cDNA_Cupcake#97]
I am working on a university HPC machine, so I did a personal install as follows:
```
module load python/3.7.2
git clone https://github.com/Magdoll/cDNA_Cupcake.git
cd cDNA_Cupcake
python3.7 setup.py build
python3.7 setup.py install --user
```

Then I checked for the files:
```
$ which collapse_isoforms_by_sam.py 
/usr/local/python/3.7.2/bin/collapse_isoforms_by_sam.py
```

Finally I ran the test case and got an error:
```
$ collapse_isoforms_by_sam.py --input cupcake/test_data/hq_isoforms.fastq --fq -s cupcake/test_data/hq_isoforms.fastq.sorted.sam --dun-merge-5-shorter -o test
Traceback (most recent call last):
  File "/usr/local/python/3.7.2/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==8.6', 'collapse_isoforms_by_sam.py')
  File "/usr/local/python/3.7.2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/python/3.7.2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/python/3.7.2/lib/python3.7/site-packages/cupcake-8.6-py3.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 26, in <module>
    from cupcake.tofu.utils import check_ids_unique
  File "/usr/local/python/3.7.2/lib/python3.7/site-packages/cupcake-8.6-py3.7-linux-x86_64.egg/cupcake/tofu/utils.py", line 13
    raise Exception, "Duplicate id {0} detected. Abort!".format(r.id)
                   ^
SyntaxError: invalid syntax
```

What am I doing wrong? I am installing cDNA_Cupcake/Tofu for use with SQANTI2 later. Any help will be much appreciated.

Best Regards,
Priyanka

**Comment by Magdoll** [comment]
Hi @psur9757 

You somehow ended up with Cupcake v8.6 which is still under Python 2.7, please update to latest version of Cupcake (version 9.0.2)
-Liz
